packages:
  - packages/*
  - apps/*

catalog:
  '@changesets/cli': ^2.29.7
  '@eslint/compat': 1.3.2
  '@eslint/js': ^9.36.0
  '@shikijs/langs': ^3.13.0
  '@shikijs/rehype': ^3.13.0
  '@shikijs/themes': ^3.13.0
  '@sveltejs/adapter-vercel': 5.10.2
  '@sveltejs/kit': ^2.43.0
  '@sveltejs/package': ^2.0.0
  '@sveltejs/vite-plugin-svelte': 6.1.3
  '@types/hast': ^3.0.4
  '@types/mdast': ^4.0.4
  '@types/node': ^22
  '@vitest/browser': 3.2.4
  concurrently: ^9.2.1
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.12.4
  globals: ^16.4.0
  hastscript: ^9.0.1
  playwright: ^1.53.0
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  property-information: 7.1.0
  publint: ^0.3.2
  rehype-raw: 7.0.0
  remark-gfm: 4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-toc: 9.0.0
  shiki: ^3.13.0
  style-to-object: 1.0.9
  svelte: ^5.5.0
  svelte-check: ^4.0.0
  typescript: ^5.0.0
  typescript-eslint: ^8.44.1
  unified: 11.0.5
  vite: 7.1.3
  vitest: 3.2.4
  vitest-browser-svelte: ^0.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@vercel/nft'
