packages:
  - packages/*

catalog:
  '@eslint/compat': 1.3.2
  '@eslint/js': ^9.22.0
  '@sveltejs/adapter-vercel': 5.10.2
  '@sveltejs/kit': 2.37.0
  '@sveltejs/package': ^2.0.0
  '@sveltejs/vite-plugin-svelte': 6.1.3
  '@types/hast': ^3.0.4
  '@types/mdast': ^4.0.4
  '@types/node': ^22
  '@vitest/browser': 3.2.4
  eslint: ^9.22.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-svelte: ^3.0.0
  esm-env: ^1.2.2
  globals: ^16.0.0
  html-url-attributes: ^3.0.1
  playwright: ^1.53.0
  prettier: ^3.4.2
  prettier-plugin-svelte: ^3.3.3
  property-information: ^7.1.0
  publint: ^0.3.2
  rehype-raw: ^7.0.0
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  style-to-object: ^1.0.9
  svelte: ^5.5.0
  svelte-check: ^4.0.0
  typescript: ^5.0.0
  typescript-eslint: ^8.20.0
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  vfile: ^6.0.3
  vite: 7.1.3
  vite-plugin-devtools-json: ^1.0.0
  vitest: 3.2.4
  vitest-browser-svelte: ^0.1.0

catalogMode: strict

minimumReleaseAge: 1440
